mixer_node:
  ros__parameters:
    mixer: # defining six channels for three motors
      bias:         [     0.0,     0.0,     0.0,     0.0,     0.0,     0.0]
      x:            [  2047.0, -2047.0,  2047.0, -2047.0,     0.0,     0.0]
      yaw:          [  2047.0, -2047.0, -2047.0,  2047.0,     0.0,     0.0]
      z:            [     0.0,     0.0,     0.0,     0.0,  2047.0, -2047.0]
    mask:           [    true,    true,    true,    true,    true,    true]

pwm_node:
  ros__parameters:
    device: "/dev/i2c-1"
    frequency: 1600
    pwm_min:        [    0,    0,    0,    0,    0,    0 ,0,0, 0,0,0,0, 0,0,0,0]
    pwm_max:        [ 4095, 4095, 4095, 4095, 4095, 4095 ,0,0, 0,0,0,0, 0,0,0,0]
    timeout_value:  [    0,    0,    0,    0,    0,    0 ,0,0, 0,0,0,0, 0,0,0,0]
